ComputerScienceHouse/Constitution

- articles.tex
Check one:
Adds keeping confidentiality as an Executive Board responsibility when a House member requests for something to be kept private, except in cases where there is a potential for harm to themselves or others. Also, adds a responsibility for Executive Board to proactively maintain a safe environment for its members
To be announced on April 17th, 2016. To be voted on April 24, 2016.
> Executive Board Confidentiality and Safe Environment

- bylaws.tex
Check one:
House was a little confused about some articles, an indefinite pronoun, consistency over proper names (which is actually a pretty deep rabbit hole that this PR does _not_ seek to address), and tense in the Evaluations Processes section. This PR addresses the non-semantic issues found therein.
> Resolving grammar problems in Evaluations Processes

- bylaws.tex
Check one:
- [ X] Non-semantic Change: Spelling, grammar, or formatting changes.
Fixed typos in by-laws
line 7: officialized -> finalized
line 279: made run on sentence into 2 separate sentences to remove comma splice
> updated typos

- articles.tex
Check one:
I think that this is truly a non-semantic change, but I understand that we have to be cautious to the changing of the constitution so this will have to be amended the traditional way.  
This amendment changes the qualifications of the OpComm Director so that they are more consistent with the rest of the Executive Board's qualifications.
> Change to qualifications of OpComm Director

- bylaws.tex
Check one:
Evaluations votes are counted as a simple majority presently, and therefore should be defined as such in the constituition. This simply ammends the simple majority requirement to evals votes wheras it was not presently defined.
> Added Simple Majority specification to Evals votes

- articles.tex
Check one:
I noticed that the Section regarding Leave's of Absence was a little long winded. I decided to break it up slightly and fix the wording of "acclimating" to "reacclimate". 
Reacclimate: To acclimate again; to reaccustom.
Acclimating: To become accustomed to a new climate or environment, the act of
> Leave of Absence Grammar

- articles.tex
Check one:
The apostrophe in the changed line in the current version of the constitution doesn't appear in a compiled version. I do not know why. I changed it to a regular single-quote character and it appears to compile as intended. 
Rip spelling mistake in commit
> swapped an apostophe for one that actually compiles

- README.md
Articles and Bylaws links were not being rendered correctly
Check one:
> Silly Markdown issue

- articles.tex
Check one:
Fixed non-voting member list under the executive board section to reflect the fact that more than one ad hoc director can exist at once.
> Corrected singular noun used in non voting eboard member section

- bylaws.tex
Check one:
The Expectations of House Members section refers to major projects two different ways, one of which is "major House project". That wording doesn't seam to appear in any other part of the constitution and isn't even consistent with the line following. The major project is well defined in the constitution and as such this is a change for consistency's sake, and doesn't change the meaning of the term.
> Fix wording inconsistency when describing major projects

- bylaws.tex
Check one:
RIT now uses a 14-week semester schedule. Update the length of the standard operating session accordingly.
> bylaws: Update standard operating session length

- articles.tex
Check one:
The Residence Halls Association is no more, so removed the reference to it. Also updated the formal name of ResLife to make is less ambiguous and change "Department" to "Center" to match their website: http://www.rit.edu/studentaffairs/reslife/
> Remove RHA, update formal name for ResLife

- bylaws.tex
Allow ad-hoc directorship meetings to count towards both
the introductory evaluations process as well as the spring
evaluations process
Wording can change need be
Check one:
> Clarify membership meeting requirements

- bylaws.tex
The max number of on-floor members didn't account for Fish.
Check one:
> Fixed estimate to account for Fish

- bylaws.tex
Check one:
Scale the permanent directorship meeting requirement based on how many semesters a member is active for. This moves the requirement in line (more or less) with the requirement for introductory members (one per week).
Things to note:
* I made the requirement fifteen per semester rather than one per week for a few reasons. The primary reason is that scaling it per week seems too fine-grained to me, and requires considerable extra bookkeeping. Scaling by week also makes the requirements per semester 14, which isn't quite as round a number as I'd like. It also made the wording slightly more cumbersome.
* I'm not convinced the wording of my change is ideal, so I'd welcome feedback on how to improve that. In particular, I want to make sure it doesn't read as …
> Scale directorship meeting requirement by semester

- articles.tex
Judicial Process automatically covers the Temporary Amendment section.
Check one:
Judicials were mentioned as the only source to make changes and interpretation to the temporary amendments section. This is pretty stupid.
> Remove Pedantic Wording

- bylaws.tex
Check one:
Removes the "essay" requirements from the intro packet. It's antiquated with no real reason to include it that I've heard other than to have a very low hurdle for freshmen. This year we had someone hit 100% on packet but "fail" packet because they didn't submit the essay. IMO, if house decides someone is good enough to get 100, that's more than enough proof that them looking at the Calendar and pubsite doesn't change anything.
> Remove 'essay' requirement from intro packet

- bylaws.tex
Check one:
- Requires signature of **all** active members (both on- and off-floor)
- Lowers requirement of alumni (non-active members), advisors, and honorary members to 10, since off-floors now count under the active member category
> Update packet signature requirements

- articles.tex
Check one:
Removes the PR Directorship (7.A.1.D) from the Temporary Amendment Changes to Evals (7.A)
> Removes the PR Directorship

- articles.tex
- bylaws.tex
Check one:
After this year without freshman project, and years of discussing removing it, I believe it is time to remove it altogether with or without the temporary amendment passing at the end of the year.
> Remove Freshman Project

- bylaws.tex
Check one:
Removes unnecessary nested enumeration from the Introductory Packet requirements section.
> Remove unneccessary enumeration from Introductory Packet requirements

- articles.tex
- bylaws.tex
Check one:
Removes the Temporary Amendment section entirely (see #143 for additional context), but retains a modified version of the Introductory Process timing change to allow for a larger application window without bringing back full rolling admissions.
Also allows us to have more than one Introductory Evaluations per year. 😂
> Remove Temporary Amendment 2: Electric Boogaloo

- bylaws.tex
Check one:
Allows the Evaluations Director to extend an Introductory Packet to accommodate extenuating circumstances. This brings the Constitution up-to-date with the processes we already have in place.
> Allow Evaluations Director to extend an Introductory Packet

- articles.tex
'standard operating session' doesen't refer to the Standard Operating
Session.
Check one:
Capitalise ‘Standard Operating Session’ so it matches the bylaws.
> Capitalise 'standard operating session'

- articles.tex
- bylaws.tex
We don't require this per the constitution
Check one:
Summary of change(s): Per the constitution, we no longer need to print, sign, notarize, and place the document in the cabinet. But it's a file change, so it's semantic.
> Remove the notarize reference

- articles.tex
Check one:
It was very inconsistent so now it's `Ad-Hoc` everywhere.
> Standardises the spelling of Ad-Hoc

- bylaws.tex
Check one:
All members who have completed all of their requirements will automatically pass their Membership Evaluation.
This stems from recent conversations, where it has sounded as though we should never not be passing a member who has objectively completed their requirements.
> Automatically pass All Green at Spring Evals

- articles.tex
By current practice, we don't restrict nomination only to qualified
members, so we should update that, so we can bring up candidates and
determine whether their merit should override the qualifications of a
seat.
Check one:
This is primarily to update to current practice. If we are going to bring up a candidate who isn't qualified and consider the possibility of an override of the qualifications, we allow them to be nominated before we do discussion and voting. This means we can bring up overrides at a House Meeting before ballots are distributed.
This change removes the requirement to be qualified from nominations and places it instead with the inclusion in ballots and the determination of winners.
> Simplify the requirements for nominations

- constitution.tex
Check one:
Summary of change(s): Capitalizing Introductory Evaluations because it's a proper term
> Capitalize Introductory Evaluations

- Makefile
Check one:
The makefile needs to build twice so that previous references are understood.
> Correct Makefile to handle references

- constitution.tex
Check one:
Summary of change(s): The description for a conditional was missing an "and." This adds it
> Add a missing 'and' to conditional description

- constitution.tex
Check one:
Deletes bad references to Housing Evals, makes housing points automatic. Also updates constitution to current process.
> Rm housing evals

- constitution.tex
Check one:
#181 and #148 would require an election in the event of the resignation of the OpComm Director, the Secretary, or any AdHoc Director. This requires their replacement to be selected via the process we usually use to select that position.
> Don't elect OpComm, Ad Hocs, or the Secretary

- constitution.tex
Check one:
Resignations -> Executive Board Resignations
Fixes undefined label warnings at compile time.
> Correct undefined Resignation references

- constitution.tex
Check one:
Reduce ambiguity in the membership eval voting section by being more specific.
> Reword ambiguous membership evaluation

- constitution.tex
Check one:
If the Intro Process is extended, that Process's Evaluation may need to occur outside of the 6th and 10th week of the semster.
> Correct inconsistency in Intro Period extensions

- constitution.tex
Check one:
We use the 'Housing Priority System' and 'Housing Priority Points'. We
don't need to also define 'Housing Points' in a different place, with a
conflicting definition.
This PR brings the constitution in line with current practice, and makes the constitution less confusing and self contradictory.
> Remove outdated 'Housing Points' and cleanup Housing Priority

- constitution.tex
Check one:
We originally introduced auto-pass in #163, which was brought up to vote, and passed.
It seems that when the documents were merged in #172, this addition was lost.
This PR introduces the same wording, in the same sub section. This is exactly the same change as #163, and I believe current practice as of last year.
The original wording of #163 was:
```
All members who have completed all of their requirements will automatically pass their Membership Evaluation.
```
> Return auto pass to the written constitution

- constitution.tex
Check one:
- [  ] Semantic Change: something about the meaning of the text is different
Added a fullstop to line 360 to make sure it's clear that it's two sentences.
> Added fullstop to line 360

- constitution.tex
Check one:
This is a semantic change and expansion based on clarifying the process where a Financial Director can provide an extension to a member for paying dues. I've expanded the section to allow the Financial Director (or eboard) to go through a series of possible solutions for active members who are having trouble paying dues.
Hit me with some critiques, this is just a rough draft and my first semantic change.
> Rough draft of redefining dues exemptions

- constitution.tex
Check one:
Summary of change(s): It's dumb that honorary members need to complete packet so this changes that.
> allow honorary and advisory members accounts without completion of packet

- Dockerfile
Check one:
Summary of change(s): Oops I forgot to add git as a build-time dependency so the last updated field on the first page is blank
> Add git as a build dependency

- constitution.tex
Check one:
These changes are a proposal to bring the introductory process timeline into the new system proposed throughout discussion this year. Instead of a ten week process, the process would now be six weeks long, and could occur twice in a semester. See https://discourse.csh.rit.edu/t/proposing-possible-changes-to-the-intro-process/130335/11 for further discussion on this topic.
> Updated introductory process timeline to new proposal

- constitution.tex
Check one:
established requirements for active members to vote at introductory evaluations. Voting members must meet the same requirement that introductory members must meet with the exception of packet, all of these requirements can be waved by the Evaluations DIrector or eboard.
> introduce requirements for active members to vote at introductory evaluations

- constitution.tex
Check one:
Requires Active Members to attend Elections with sufficient notice. Attendance will be taken in the same manner as a House Meeting, with a 5 day notice required by E-Board.
> Add Active Member Requirement for Elections

- constitution.tex
Check one:
Made it clear that only a majority of voting Eboard members must be present.
> Clarifies the voting members must be Eboard

- constitution.tex
Check one:
removed the line that stated membership evaluations where bi-annual
removed the line that said we would kick failed members off floor
> updated the constitution to reflect current spring evals process

- constitution.tex
Check one:
changes Bad Standing votes so that they are held during House Meeting
> Reform Alumni in bad standing votes

- constitution.tex
Check one:
fixes the wording to eliminate edge case that allows active members who have not passes an intro evals to be a required signature
> fixes the wording to eliminate edge case in 5.D.3.C.b

- constitution.tex
Check one:
table of contents numbers are correct now
> table of contents numbers now start at correct page number

- constitution.tex
Check one:
This change prevents current active and alumni members from reentering the introductory process, thereby preventing an opportunity for constitutional ambiguity.
> prevent multiple simultaneous memberships

- constitution.tex
Check one:
Allow off floor intro members to sign packets.
Also fixes wording about which active members are expected to sign packets in order to make it simpler and clearer
> Allow off floor intro members to sign packets

- constitution.tex
Check one:
Gave amendments and overrides their own sections in the semantic changes section.
> Different section for Amendments and Overrides

- constitution.tex
Check one:
Condensed 4.D.4 and 4.D.5 for consistency, since they state the same thing for advisory and honorary members
> Condense 4.D.4 and 4.D.5

- constitution.tex
Check one:
closes #258
removes mentions of interviews from the intro process for Incoming RIT students
> remove interview mentions from 4.A.2.B
