bylaws.tex
Check one:
- Remove freshmen signatures from packet.
=> Remove Freshmen Signatures from Packet

README.md
Check one:
Changes to README.md
4. Compile the `.tex` files into `.pdf` files.
6. Announce the amendment at House Meeting.
=> Updated Steps in README.md

articles.tex, bylaws.tex
Check one:
A collection of non-semantic fixes that mostly deal with whitespace.
=> Various Non Semantic Fixes

articles.tex
Check one:
Due to wording not being specific enough, some were confused about the meaning of the altered text. With the approval of Executive Board, this text has been modified to more clearly describe how the process works.
=> Specify 'Votes Collected'

articles.tex
Check one:
- [ x] Non-semantic Change: Spelling, grammar, or formatting changes.
Fixed small thing brought up by @nick
=> collected -> cast

Makefile
Check one:
Fixed the Makefile to correct the inter-article linking issues we were having. (no more "??").
=> Updated Makefile to fix inter-linking compilation issues

articles.tex, bylaws.tex
Check one:
Removed all trailing white spaces from the .tex files.
=> Removed all trailing whitespacs from .tex files

Makefile
=> Fix Git Revision Insertion for Makefile

articles.tex, bylaws.tex
Check one:
"introductory members"->"Introductory members"
Added/removed some periods.
=> Fixed periods and capitalization

README.md
Check one:
Added more instructions on working with the constitution to the readme.
=> Add more instructions to readme

.gitignore, articles.tex, bylaws.tex
Check one:
Add a table of contents to the articles and by-laws.
=> Add table of contents to articles/bylaws

bylaws.tex
Check one:
I'm honestly not sure if you'd describe this as semantic or not - it seems non-semantic to me. We could remove the inconsistency now and then change it later.
=> Clarify introductory membership terms

bylaws.tex
Check one:
Update Expectations of House Members to reflect current practice
=> Updated Expectations of House Members

bylaws.tex
Check one:
Fixing merge conflicts from #122 (which was approved)
=> Fix Merge Issues from #122

articles.tex
Check one:
Fixes some weird grammar in the first bullet point under "Responsibilities of the Financial Directory" regarding the Financial Meeting.
My fix of the grammar may not be the best, feel free to correct it/suggest alternatives. :call_me_hand:
=> Fix wording in Responsibilities of Directors sections

articles.tex
Check one:
* PR Directorship Created
* PR Directorship is given a budget of 5% of total funds
* Packet % increased to 75% 
* Packet is delayed a week. 
* Packets are no longer given out after week 2 and are due by the end of week 3. 
* Removal of Freshman Project
* Each semester the process repeats 
With this, some other changes will happen but they aren't constitutional in nature.
=> Changes to Evaluations

articles.tex
Check one:
Just make it clear they're resigning their board position and not their membership.
=> Clarifies Resignation

articles.tex
Check one:
No one knows what this means. 🥇
=> Secretary Responsibilities Update

articles.tex
Check one:
Fixing Inconsistent Membership referencing #52
=> Fixing Inconsistent Membership Status

articles.tex
Check one:
Summary of change(s): The secretary can't do their job it they aren't in eboard meetings, so this adds the House Secretary to the list of people allowed in closed.
=> Allow the Secretary to do their job

articles.tex
Reverts ComputerScienceHouse/Constitution#157
=> Revert "Allow the Secretary to do their job"

bylaws.tex
Check one:
Make Spring Objective (for reals)
=> Spring is Objective

.travis.yml
https://s3.csh.rit.edu/uploads/articles.pdf
https://s3.csh.rit.edu/uploads/bylaws.pdf
=> Use Travis CI to compile documents to PDFs and upload them to S3

constitution.tex
This has already passed but it needed to be updated.
Check one:
=> Elections are Mandatory

constitution.tex
Check one:
Changes introductory members being required to pay dues.
=> Make intro members not required to pay dues

Dockerfile
Check one:
Make the Dockerfile work with the proper image version
At request of @galenguyer
=> Update Version of nginx image

constitution.tex
Check one:
By-laws don't exist anymore, we shouldn't still refer to them here.
=> constitution: by-laws don't exist anymore

constitution.tex
Check one:
Summary of change(s): Adds a Public Relations Director to the Executive board, enumerates the responsibilities of the position, and sets the budget for the position at 5% of the total, taking that 5% from the Social Director.
=> Add a Public Relations Director to the Executive Board

.gitignore, Dockerfile, README.md, constitution.tex, nginx.conf
Check one:
Reworked the entire document to make it more readable, more logically organized, and ensure the content is accurate and reflects current practice. 
A more detailed list of changes can be found here https://discourse.csh.rit.edu/t/constitutional-rewrite-amendment-proposal/131387
Also, the compiled pdf of this version is hosted at https://new-constitution.cs.house/
=> Rewrite Amendment

.github/workflows/release.yml
Check one:
Now when changes are pushed to master, they are turned into a release named "Amendment $DATE". If more than one push happens on one day, it'll replace the old one.
=> Add CI/CD PDF Workflow

constitution.tex
Check one:
make dollar amounts consistent
=> make dollar amounts consistent

constitution.tex
- **voting member requirements**
Check one:
Eligible Votes contains a reference to Voting Member Requirements (gatekeep)
The wording of Section 5.B.4 removes the Eligible Votes, and includes Voting Eboard Members
=> voting member requirements
